# **Задание**

В этом задании вам предстоит обучить модель для прогнозироввания стоимости недвижимости и для нее интерфейс в **Streamlit**.

Вам нужно:
1. Скачать данные и обучить модель прогнозирования стоимости недвижимости (модель может быть любой сложности, даже линейная регрессия на двух признаках) - 2 балла
2. Реализуйте код для получения предсказания обученной моделью - 1 балл
3. Реализуйте интерфейс с помощью streamlit для введения значений признаков для прогнозирования - 5 баллов
4. Реализуйте отображение результата прогнозирования в интерфейсе по нажатию кнопки - 2 балла

## Импортирование библиотек

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

## **1. Считываем датасет**

In [ ]:
# Считываем датасет
df = pd.read_csv('/content/realty_data.csv')
df.head()

product_name  period      price  postcode  \
0  3-комнатная, 137 м²     NaN   63000000  127473.0   
1      Студия, 16,7 м²     NaN    3250000  108815.0   
2   3-комнатная, 76 м²     NaN   16004680       NaN   
3   1-комнатная, 24 м²     NaN    7841776       NaN   
4  3-комнатная, 126 м²     NaN  120000000  121352.0   

                   address_name        lat        lon object_type  \
0  2-й Щемиловский переулок, 5а  55.778894  37.608844    Квартира   
1               Харлампиева, 46  55.551025  37.313054    Квартира   
2             ЖК Прокшино, 8 к4  55.594802  37.431264    Квартира   
3             ЖК Прокшино, 6 к2  55.594332  37.428099    Квартира   
4              Давыдковская, 18  55.721097  37.464342    Квартира   

   total_square  rooms  floor    city settlement                  district  \
0         137.0    3.0    6.0  Москва        NaN            Тверской район   
1          16.7    NaN    1.0  Москва        NaN  Филимонковское поселение   
2          76.0    3.0    6.0  Москва        NaN       Сосенское поселение   
3          24.0    1.0   10.0  Москва        NaN       Сосенское поселение   
4         126.0    3.0   16.0  Москва        NaN      Фили-Давыдково район   

  area                                        description               source  
0  NaN  Просторная квартира свободной планировки с пан...                 ЦИАН  
1  NaN             ВНИМАНИЕ! ОЧЕНЬ ПРИВЛЕКАТЕЛЬНОЕ ПРЕ...              Домклик  
2  NaN  Apт.1684018. 0,01% - гибкая ипотека! Воспользу...  Яндекс.Недвижимость  
3  NaN  Продается однокомнатная квартира № 381 в новос...          Новострой-М  
4  NaN  Шикарное предложение!\nПродаётся трёхкомнатная...              Домклик

### Уникальные данные в столбцах

In [ ]:
# Уникальные значения объекта
df['object_type'].unique()

array(['Квартира'], dtype=object)

In [ ]:
df['settlement'].unique()

array([nan, 'д.\xa0Мисайлово', 'пос.\xa0ВНИИССОК', 'рп.\xa0Дрожжино',
       'рп.\xa0Октябрьский', 'с.\xa0Немчиновка', 'рп.\xa0Новоивановское',
       'пос.\xa0Ильинское-Усово', 'рп.\xa0Томилино', 'рп.\xa0Боброво',
       'с.\xa0Домодедово', 'пос.\xa0Мебельной фабрики', 'д.\xa0Путилково',
       'пос.\xa0Развилка', 'д.\xa0Островцы', 'д.\xa0Большие Жеребцы',
       'пос.\xa0Коммунарка', 'д.\xa0Раздоры', 'д.\xa0Мотяково',
       'пос.\xa0Нагорное', 'пос.\xa0Марьино', 'дп.\xa0Красково',
       'рп.\xa0Лопатино', 'д.\xa0Сосенки', 'пос.\xa0Битца',
       'рп.\xa0Заречье', 'с.\xa0Ромашково', 'д.\xa0Жабкино',
       'д.\xa0Сапроново', 'пос.\xa0Отрадное', 'дп.\xa0Лесной Городок',
       'д.\xa0Мякинино', 'рп.\xa0Нахабино', 'д.\xa0Сабурово',
       'с.\xa0Николо-Урюпино', 'пос.\xa0Мирный',
       'пос.\xa0подсобного хозяйства "Воскресенское"', 'с.\xa0Молоково',
       'д.\xa0Глухово', 'д.\xa0Пирогово', 'д.\xa0Аристово',
       'д.\xa0Подолино', 'д.\xa0Солманово', 'рп.\xa0Бутово',
       'д.\xa0

In [ ]:
# Уникальные значения городов
# Видно что есть nan, в дальнейшем будет заменен
df['city'].unique()

array(['Москва', nan, 'Балашиха', 'Люберцы', 'Красногорск', 'Химки',
       'Королёв', 'Мытищи', 'Пушкино', 'Котельники', 'Одинцово',
       'Щёлково', 'Дзержинский', 'Реутов', 'Ивантеевка', 'Московский',
       'Лобня', 'Долгопрудный', 'Щербинка', 'Подольск', 'Видное',
       'Лыткарино'], dtype=object)

In [ ]:
total_square = df['total_square'].unique()

In [ ]:
# Минимальное и максимальное значение площади квартиры
print(min(total_square))
print(max(total_square))

8.0
2070.0


In [ ]:
# Уникальные значения количества комнат
df['rooms'].unique()

array([ 3., nan,  1.,  2.,  4.,  5.,  6., 10.,  7., 11.,  8.,  9., 12.,
       14., 15., 13.])

In [ ]:
# Уникальные значения этажа
df['floor'].unique()

array([ 6.,  1., 10., 16., 14.,  3., 11.,  4., 21., 12.,  8.,  2., 17.,
       19.,  7., 24.,  5., 20.,  9., 13., 30., 32., 18., 29., 15., 34.,
       23., 38., 25., 37., 42., 26., 43., 22., 33., 40., 27., 44., 52.,
       49., 31., 28., 45., 41., 48., 53., 47., 36., 51., 54., 35., 39.,
       57., 46., 66., 50., 55., 58., 56., 63., 62.])

In [ ]:
# Уникальные значения местонахождения
df['area'].unique()

array([nan, 'Железнодорожный\xa0м-н', 'Самолёт\xa0м-н',
       'Переделкино Ближнее\xa0м-н', 'Павшинская пойма\xa0м-н',
       'Старые Химки\xa0м-н', 'Юбилейный\xa0м-н', '24-й\xa0м-н',
       'Бутово парк 2\xa0м-н', 'Микрорайон Немчиновка\xa0жилой комплекс',
       'Терехово (бывш.)\xa0д.', 'Силикат\xa0м-н',
       'Люберецкие Поля\xa0м-н', 'Белая Дача\xa0м-н',
       'Левобережный\xa0м-н', 'Новое Измайлово\xa0квартал',
       'Текстильщик\xa0м-н', 'Богородский\xa0м-н', 'СГШ\xa0м-н',
       'Центральный\xa0м-н', '9а\xa0м-н', 'Птицефабрика\xa0м-н',
       'Восточное Бутово\xa0м-н', 'Домодедово Парк\xa0жилой комплекс',
       'Первый Московский Город Парк\xa0жилой комплекс',
       'Изумрудные холмы\xa0жилой комплекс',
       'Мортонград Путилково\xa0м-н', 'Новые Химки\xa0м-н',
       'Одинбург\xa0м-н', 'Подлипки\xa0м-н', 'Букино\xa0м-н',
       'Одинцово-1\xa0м-н', 'Мамонтовка\xa0м-н', 'Балашиха-1\xa0м-н',
       'Царицыно\xa0жилой комплекс', 'Водники\xa0м-н', 'Павлино\xa0м-н',
       '

In [ ]:
df['district'].unique()

array(['Тверской район', 'Филимонковское поселение',
       'Сосенское поселение', 'Фили-Давыдково район', nan,
       'Марфино район', 'Строгино район', 'Нижегородский район',
       'Внуковское поселение', 'Таганский район', 'Раменки район',
       'Чертаново Центральное район', 'Северное Бутово район',
       'Северное Медведково район', 'Гольяново район',
       'Пресненский район', 'Сокольники район', 'Митино район',
       'Нагатинский Затон район', 'Хорошёвский район',
       'Южнопортовый район', 'Марьина Роща район', 'Головинский район',
       'Ярославский район', 'Ивановское район', 'Южное Бутово район',
       'Хорошёво-Мнёвники район', 'Покровское-Стрешнево район',
       'Красносельский район', 'Некрасовка район',
       'Очаково-Матвеевское район', 'Северный район',
       'Текстильщики район', 'Мещанский район', 'Котловка район',
       'Беговой район', 'Замоскворечье район', 'Выхино-Жулебино район',
       'Коньково район', 'Тёплый Стан район', 'Свиблово район',
      

# Лишние столбцы

In [ ]:
# Удалим столбцы лишние столбцы

# product_name - так как эти данные дублируются в столбцах total_square и rooms
# period - везде значение NaN
# postcode
# address_name - территориальные данные можно взять из city
# lat - долгота
# lon - широта
# object_type - Везде слово "Квартира"
# settlement
# district
# area
# description
# source

In [ ]:
list_drop = ['product_name',
              'period',
              'postcode',
              'address_name',
              'lat',
              'lon',
              'object_type',
              'settlement',
              'district',
              'area',
              'description',
              'source']

In [ ]:
df = df.drop(list_drop, axis=1)
df.head()

price  total_square  rooms  floor    city
0   63000000         137.0    3.0    6.0  Москва
1    3250000          16.7    NaN    1.0  Москва
2   16004680          76.0    3.0    6.0  Москва
3    7841776          24.0    1.0   10.0  Москва
4  120000000         126.0    3.0   16.0  Москва

In [ ]:
# Число пустых значений
df.isna().sum()

price              0
total_square       0
rooms           3982
floor              0
city            6894
dtype: int64

### Замена всех NaN значений в столбцах rooms и city

In [ ]:
# Будем считать что если не указано количетсво комнат, то это будет 1
df["rooms"] = df["rooms"].fillna(1)

In [ ]:
df["city"] = df["city"].fillna("Не указано")

In [ ]:
df['city'].unique()

array(['Москва', 'Не указано', 'Балашиха', 'Люберцы', 'Красногорск',
       'Химки', 'Королёв', 'Мытищи', 'Пушкино', 'Котельники', 'Одинцово',
       'Щёлково', 'Дзержинский', 'Реутов', 'Ивантеевка', 'Московский',
       'Лобня', 'Долгопрудный', 'Щербинка', 'Подольск', 'Видное',
       'Лыткарино'], dtype=object)

In [ ]:
# Число пустых значений
df.isna().sum()

price           0
total_square    0
rooms           0
floor           0
city            0
dtype: int64

### Преобразование данных в численные значения

In [ ]:
# Преобразуем столбец 'city' в бинарные признаки
df = pd.get_dummies(df, columns=['city'])

In [ ]:
# Преобразование столбца 'city' в численные значения

# Создаём экземпляр LabelEncoder
encoder = LabelEncoder()

# Преобразуем столбец 'city' в числовые значения
df['city'] = encoder.fit_transform(df['city'])

print(df['city'].unique())

[11 14  0 10  7 19  5 13 17  6 15 21  2 18  4 12  8  3 20 16  1  9]


In [ ]:
df.head()

price  total_square  rooms  floor  city
0   63000000         137.0    3.0    6.0    11
1    3250000          16.7    1.0    1.0    11
2   16004680          76.0    3.0    6.0    11
3    7841776          24.0    1.0   10.0    11
4  120000000         126.0    3.0   16.0    11

In [ ]:
# Сохраняем DataFrame в формат CSV
df.to_csv('data.csv', index=False)

# **Обучение модели**

In [ ]:
def prepare_data():
  #train = pd.read_csv("data/realty_data.csv")
  train = pd.read_csv("realty_data.csv")

  list_drop = ['product_name',
              'period',
              'postcode',
              'address_name',
              'lat',
              'lon',
              'object_type',
              'settlement',
              'district',
              'area',
              'description',
              'source']

  train = train.drop(list_drop, axis=1)

  train["rooms"] = train["rooms"].fillna(1)
  train["city"] = train["city"].fillna("Не указано")

  train['rooms'] = train['rooms'].astype(int)
  train['floor'] = train['floor'].astype(int)

  train = pd.get_dummies(train, drop_first=False)
  # encoder = LabelEncoder()
  # df['city'] = encoder.fit_transform(df['city'])

  return train

In [ ]:
import os
import pickle

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.pipeline import Pipeline

def prepare_data():
    train = pd.read_csv("/content/data_get_dummies.csv")

    return train

def train_model(train):
    X, y = train.drop("price", axis=1), train['price']

    pipeline = Pipeline([("rf_reg", RandomForestRegressor(random_state=42))])

    param_dist = {
        "rf_reg__n_estimators": np.arange(200, 2001, 200),
        "rf_reg__max_features": ["auto", "sqrt", "log2"],
        "rf_reg__max_depth": list(np.arange(10, 101, 10)) + [None],
        "rf_reg__min_samples_split": [2, 5, 10],
        "rf_reg__min_samples_leaf": [1, 2, 4, 8],
        "rf_reg__bootstrap": [True, False]
    }

    rf = RandomizedSearchCV(
        pipeline,
        param_dist,
        cv=5,
        n_iter=1, # 50
        n_jobs=4,
        verbose=1,
    )
    rf.fit(X, y)

    with open('rf_ForestRegressor.pkl', 'wb') as file:
        pickle.dump(rf, file)

def read_model(model_path):
    if not os.path.exists(model_path):
        raise FileNotFoundError("Model file not exists")

    with open(model_path, 'rb') as file:
        model = pickle.load(file)

    return model

train_data = prepare_data()
train_model(train_data)

#model = read_model('rf_fitted.pkl')

Fitting 5 folds for each of 1 candidates, totalling 5 fits


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(


# Мой streamlit

In [ ]:
train_data = prepare_data()
train_data.to_csv('my_data.csv')
train_data.head()

price  total_square  rooms  floor  city_Балашиха  city_Видное  \
0   63000000         137.0      3      6          False        False   
1    3250000          16.7      1      1          False        False   
2   16004680          76.0      3      6          False        False   
3    7841776          24.0      1     10          False        False   
4  120000000         126.0      3     16          False        False   

   city_Дзержинский  city_Долгопрудный  city_Ивантеевка  city_Королёв  ...  \
0             False              False            False         False  ...   
1             False              False            False         False  ...   
2             False              False            False         False  ...   
3             False              False            False         False  ...   
4             False              False            False         False  ...   

   city_Московский  city_Мытищи  city_Не указано  city_Одинцово  \
0            False        False            False          False   
1            False        False            False          False   
2            False        False            False          False   
3            False        False            False          False   
4            False        False            False          False   

   city_Подольск  city_Пушкино  city_Реутов  city_Химки  city_Щербинка  \
0          False         False        False       False          False   
1          False         False        False       False          False   
2          False         False        False       False          False   
3          False         False        False       False          False   
4          False         False        False       False          False   

   city_Щёлково  
0         False  
1         False  
2         False  
3         False  
4         False  

[5 rows x 26 columns]

In [ ]:
list(train_data.columns)

['Unnamed: 0',
 'price',
 'total_square',
 'rooms',
 'floor',
 'city_Балашиха',
 'city_Видное',
 'city_Дзержинский',
 'city_Долгопрудный',
 'city_Ивантеевка',
 'city_Королёв',
 'city_Котельники',
 'city_Красногорск',
 'city_Лобня',
 'city_Лыткарино',
 'city_Люберцы',
 'city_Москва',
 'city_Московский',
 'city_Мытищи',
 'city_Не указано',
 'city_Одинцово',
 'city_Подольск',
 'city_Пушкино',
 'city_Реутов',
 'city_Химки',
 'city_Щербинка',
 'city_Щёлково']

In [ ]:
train_data = prepare_data()
train_data.head()

Survived  Age  child  family_size  Pclass_1  Pclass_2  Pclass_3  \
0         0   22      0            2     False     False      True   
1         1   38      0            2      True     False     False   
2         1   26      0            1     False     False      True   
3         1   35      0            2      True     False     False   
4         0   35      0            1     False     False      True   

   Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S  
0       False      True       False       False        True  
1        True     False        True       False       False  
2        True     False       False       False        True  
3        True     False       False       False        True  
4       False      True       False       False        True

In [ ]:
import os

import pandas as pd
import streamlit as st

#from src.utils import prepare_data, train_model, read_model

st.set_page_config(
    page_title="Housing valuation",
)

model_path = '/content/rf_fitted_get_dummies.pkl'

# Общая площадь
total_square = st.sidebar.number_input("Total area",
                                       min_value=8.0,
                                       max_value=2070.0,
                                       value=50.0,
                                       step=1.0)
# Количество комнат
rooms = st.sidebar.number_input(
    "How many rooms in the flat?",
    1, 13, 1,
)

# Этаж
floor = st.sidebar.number_input(
    "What floor the flat is on?",
    1, 63, 1)


# Город
city = st.sidebar.selectbox(
    "In which city the flat is located?",
    ('Не указано',
     'Балашиха',
     'Видное',
     'Дзержинский',
     'Долгопрудный',
     'Ивантеевка',
     'Королёв',
     'Котельники',
     'Красногорск',
     'Лобня',
     'Лыткарино',
     'Люберцы',
     'Москва',
     'Московский',
     'Мытищи',
     'Одинцово',
     'Подольск',
     'Пушкино',
     'Реутов',
     'Химки',
     'Щербинка',
     'Щёлково'),
)

inputDF = pd.DataFrame(
    {
        "total_square": total_square,
        "rooms": rooms,
        "floor": floor,
        'city_Балашиха': city == 'Балашиха',
        'city_Видное': city == 'Видное',
        'city_Дзержинский': city ==  'Дзержинский',
        'city_Долгопрудный': city == 'Долгопрудный',
        'city_Ивантеевка': city == 'Ивантеевка',
        'city_Королёв': city == 'Королёв',
        'city_Котельники': city == 'Котельники',
        'city_Красногорск': city == 'Красногорск',
        'city_Лобня': city == 'Лобня',
        'city_Лыткарино': city == 'Лыткарино',
        'city_Люберцы': city == 'Люберцы',
        'city_Москва': city == 'Москва',
        'city_Московский': city == 'Московский',
        'city_Мытищи': city == 'Мытищи',
        'city_Не указано': city == 'Не указано',
        'city_Одинцово': city == 'Одинцово',
        'city_Подольск': city == 'Подольск',
        'city_Пушкино': city == 'Пушкино',
        'city_Реутов': city == 'Реутов',
        'city_Химки': city == 'Химки',
        'city_Щербинка': city == 'Щербинка',
        'city_Щёлково': city == 'Щёлково',

    },
    index=[0],
)

if not os.path.exists(model_path):
    train_data = prepare_data()
    train_data.to_csv('data.csv')
    train_model(train_data)

model = read_model('rf_ForestRegressor.pkl')

preds = model.predict_proba(inputDF)[0, 1]
preds = round(preds * 100, 1)


st.image("imgs/Housing valuation.png", use_column_width=True)
st.write(f"The cost of the selected accommodation consists of: {preds}%")